spring:
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
    static-path-pattern: /**
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/transactions?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.leon.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml


